### ISSUE TITLE
It's an infinite loop.

### ISSUE THREAD

**Issue by anohren** [MediaBrowser/website#17]
I install the Kodi plugin by following the instructions on the download page. I then go to Support - Wiki - Emby Apps - Kodi with the expectation to be presented with an actual wiki page (since I'm in the wiki) so that I can read up on it. Instead I get redirected back to the download page...

**Comment by LukePulverenti** [comment]
Thanks. The wiki page has been updated to bring you to the kodi specific download page, which we will update with wiki links for that app.
