### ISSUE TITLE
Broken link in the TV Naming Section

### ISSUE THREAD

**Issue by xsteacy** [MediaBrowser/website#23]
Hi,

I found a broken link in the TV naming section under "Specials", There's a TIP with that link:
"[Ordering TV Show Special/Extras](https://emby.freshdesk.com/a/solutions/articles/44001904299)"
I tried to search for it in the support section to repair it but I had no luck.
I someone can give me the working link I can submit a pull request with the correct one.

Thank you ;)

**Comment by ebr11** [comment]
Hi.  Is it working for you now?

**Comment by xsteacy** [comment]
Yes!
Thank you
