### ISSUE TITLE
linux-server.html needs slight editing

### ISSUE THREAD

**Issue by ganastor** [MediaBrowser/website#4]
Referring to the Docker portion - the first line needs to be broken into 2 lines as running it as a single command obviously won't work.

Also, after starting it for the first time it requests to set the media paths before the localhost:8096 will launch, so the easy answer here would be to type "done" after running the start command. I imagine this shouldn't be required so I didn't want to put in a pull, but the easy solution for both is below (starting at line 256).

<p><code>docker run -it --rm -v /usr/local/bin:/target \
        <p>emby/embyserver instl</code></p>
<div><strong>Run Emby Server</strong></div>
<p><code>/usr/local/bin/emby-server
<p>done</code></p>

**Comment by hurricanehrndz** [comment]
If you type in just done without providing media locations, the container will not have any access to the host's media files. I'm sorry but I strongly disagree with your suggestion. We would then have a bunch of users asking how could they access their media.

**Comment by ganastor** [comment]
Perfectly understood, that's why I didn't want to enter a pull request, but it should state something about that here as you can't just run /usr/local/bin/emby-server then open up localhost:8096 - it won't open until the paths are entered.

To my first note, currently the docker run is on one line on the website, which won't work with the "\" in there:

<code>docker run -it --rm -v /usr/local/bin:/target \ emby/embyserver instl</code>

**Comment by hurricanehrndz** [comment]
Yes, you are right. about the slash. We will add a not about answering the prompts from the wrapper script.

**Comment by ganastor** [comment]
Sounds good!
