### ISSUE TITLE
Some more info on download page

### ISSUE THREAD

**Issue by thenktor** [MediaBrowser/website#7]
On the download page there is a quick info how to install, start and setup Emby server on Linux hosts. I've installed Emby on a Debian 8 box and noticed that the Emby service is not started at system boot. Also the info how to enable it is missing on the download page and IMHO should be there:

**Enable Emby Server at system start:**
`sudo systemctl enable emby-server.service`

**Comment by Night1** [comment]
/etc/init.d/emby-server start
 

in rc.local works aswell, I have that on my debian based server.

**Comment by Night1** [comment]
`<div><strong>Start Emby during startups</strong></div>
By defualt Emby does not start by it self on boot to achieve this simply edit your rc.local in /etc/ and add<code><p>/etc/init.d/emby-server start</code></p>`


That is applicable for CentOS, Debian, Ubuntu, Fedora. 

Ill find the rest and create a pull request.
